import type { ZoneDefinition } from "./types";

/**  */
/**
 * Starting zone - the default spawn area for new players.
 */
export const ZONE_STARTING_PLAINS: ZoneDefinition = {
  id: "startingPlains",
  name: "Starting Plains",
  sceneData: {
    navmeshFilePath: "startingPlains.navcat.json",
    navmeshGeneration: {
      cellSize: 0.15,
      cellHeight: 0.25,
      walkableRadiusWorld: 0.3,
      walkableHeightWorld: 2,
      walkableClimbWorld: 0.5,
      walkableSlopeAngleDegrees: 45,
      minRegionArea: 8,
      mergeRegionArea: 20,
      maxSimplificationError: 1.3,
      maxEdgeLength: 12,
      maxVerticesPerPoly: 5,
      detailSampleDistanceVoxels: 6,
      detailSampleMaxErrorVoxels: 1,
      borderSize: 0,
    },
    width: 100,
    height: 100,
    ground: {
      color: { r: 0.3, g: 0.5, b: 0.3 },
      gridColor: { r: 0.2, g: 0.3, b: 0.2 },
      gridSize: 10,
      splat: {
        mixTexture: {
          url: "startingPlains.mix.v2.png",
        },
        diffuseTexture1: {
          url: "Grass_01.png",
          tileSize: 4,
        },
        diffuseTexture2: {
          url: "Dirt_02.png",
          tileSize: 4,
        },
        diffuseTexture3: {
          url: "Dirt_01.png",
          tileSize: 4,
        },
      },
      water: {
        x: -14,
        z: 12,
        width: 16,
        height: 10,
        yOffset: 0.05,
        alpha: 0.7,
        color: { r: 0.1, g: 0.45, b: 0.65 },
        texture: {
          builtIn: "proceduralWater",
          tileSize: 4,
        },
      },
      heightMap: {
        builtIn: "proceduralHills",
        url: "startingPlains.height.png",
        size: 256,
        subdivisions: 128,
        minHeight: -2.5,
        maxHeight: 2.5,
      },
    },
    terrainObjects: [
      {
        id: "obstacle_1",
        x: 5,
        z: 5,
        shape: "box",
        size: 1.5,
        collidable: true,
        label: "Red Crate",
        color: { r: 0.8, g: 0.2, b: 0.2 },
      },
      {
        id: "pickup_1",
        x: -8,
        z: 3,
        shape: "sphere",
        size: 0.8,
        collidable: false,
        label: "Blue Orb",
        color: { r: 0.2, g: 0.4, b: 0.9 },
      },
      {
        id: "pillar_1",
        x: 0,
        z: -10,
        shape: "cylinder",
        size: 2,
        collidable: true,
        label: "Green Pillar",
        color: { r: 0.2, g: 0.7, b: 0.3 },
      },
      {
        id: "chest_1",
        x: -5,
        z: -5,
        shape: "box",
        size: 1,
        collidable: true,
        label: "Treasure Chest",
        color: { r: 0.9, g: 0.8, b: 0.2 },
      },
      {
        id: "orb_1",
        x: 12,
        z: -3,
        shape: "sphere",
        size: 1.2,
        collidable: true,
        label: "Magic Orb",
        color: { r: 0.6, g: 0.2, b: 0.8 },
      },
      {
        id: "house_1",
        x: -18,
        z: 16,
        shape: "box",
        size: 8,
        collidable: true,
        label: "House A",
        color: { r: 0.45, g: 0.4, b: 0.35 },
      },
      {
        id: "house_2",
        x: 22,
        z: 8,
        shape: "box",
        size: 10,
        collidable: true,
        label: "House B",
        color: { r: 0.4, g: 0.42, b: 0.48 },
      },
      {
        id: "house_3",
        x: 6,
        z: -22,
        shape: "box",
        size: 9,
        collidable: true,
        label: "House C",
        color: { r: 0.5, g: 0.46, b: 0.4 },
      },
    ],
  },
};
